-- Migration: Add Comprehensive Exercises
INSERT INTO exercises (name, muscle_group, equipment, animation_url, description) VALUES
('Flat Chest Press Machine', 'Chest', 'Machine', '', 'The Flat Chest Press Machine represents a machine exercise primarily targeting the Chest.'),
('Incline Chest Press Machine', 'Chest', 'Machine', '', 'The Incline Chest Press Machine represents a machine exercise primarily targeting the Chest.'),
('Decline Chest Press Machine', 'Chest', 'Machine', '', 'The Decline Chest Press Machine represents a machine exercise primarily targeting the Chest.'),
('Iso-Lateral Chest Press', 'Chest', 'Machine', '', 'The Iso-Lateral Chest Press represents a machine exercise primarily targeting the Chest.'),
('Hammer Strength Chest Press', 'Chest', 'Machine', '', 'The Hammer Strength Chest Press represents a machine exercise primarily targeting the Chest.'),
('Hammer Strength Incline Press', 'Chest', 'Machine', '', 'The Hammer Strength Incline Press represents a machine exercise primarily targeting the Chest.'),
('Converging Chest Press', 'Chest', 'Machine', '', 'The Converging Chest Press represents a machine exercise primarily targeting the Chest.'),
('Seated Chest Press', 'Chest', 'Machine', '', 'The Seated Chest Press represents a machine exercise primarily targeting the Chest.'),
('Vertical Chest Press', 'Chest', 'Machine', '', 'The Vertical Chest Press represents a machine exercise primarily targeting the Chest.'),
('Pec Deck (Rear-Entry)', 'Chest', 'Machine', '', 'The Pec Deck (Rear-Entry) represents a machine exercise primarily targeting the Chest.'),
('Pec Deck (Front-Entry)', 'Chest', 'Machine', '', 'The Pec Deck (Front-Entry) represents a machine exercise primarily targeting the Chest.'),
('Pec Fly Machine', 'Chest', 'Machine', '', 'The Pec Fly Machine represents a machine exercise primarily targeting the Chest.'),
('Incline Pec Fly Machine', 'Chest', 'Machine', '', 'The Incline Pec Fly Machine represents a machine exercise primarily targeting the Chest.'),
('Decline Pec Fly Machine', 'Chest', 'Machine', '', 'The Decline Pec Fly Machine represents a machine exercise primarily targeting the Chest.'),
('Cable Chest Fly (High-to-Low)', 'Chest', 'Cable', '', 'The Cable Chest Fly (High-to-Low) represents a cable exercise primarily targeting the Chest.'),
('Cable Chest Fly (Low-to-High)', 'Chest', 'Cable', '', 'The Cable Chest Fly (Low-to-High) represents a cable exercise primarily targeting the Chest.'),
('Cable Chest Fly (Mid-Cable)', 'Chest', 'Cable', '', 'The Cable Chest Fly (Mid-Cable) represents a cable exercise primarily targeting the Chest.'),
('Single-Arm Cable Fly', 'Chest', 'Cable', '', 'The Single-Arm Cable Fly represents a cable exercise primarily targeting the Chest.'),
('Cable Press (Standing)', 'Chest', 'Cable', '', 'The Cable Press (Standing) represents a cable exercise primarily targeting the Chest.'),
('Cable Press (Seated Bench)', 'Chest', 'Cable', '', 'The Cable Press (Seated Bench) represents a cable exercise primarily targeting the Chest.'),
('Cable Crossover (Wide Stance)', 'Chest', 'Cable', '', 'The Cable Crossover (Wide Stance) represents a cable exercise primarily targeting the Chest.'),
('Cable Crossover (Narrow Stance)', 'Chest', 'Cable', '', 'The Cable Crossover (Narrow Stance) represents a cable exercise primarily targeting the Chest.'),
('Incline Cable Press', 'Chest', 'Cable', '', 'The Incline Cable Press represents a cable exercise primarily targeting the Chest.'),
('Flat Barbell Bench Press', 'Chest', 'Barbell', '', 'The Flat Barbell Bench Press represents a barbell exercise primarily targeting the Chest.'),
('Incline Barbell Bench Press', 'Chest', 'Barbell', '', 'The Incline Barbell Bench Press represents a barbell exercise primarily targeting the Chest.'),
('Decline Barbell Bench Press', 'Chest', 'Barbell', '', 'The Decline Barbell Bench Press represents a barbell exercise primarily targeting the Chest.'),
('Reverse-Grip Bench Press', 'Chest', 'Barbell', '', 'The Reverse-Grip Bench Press represents a barbell exercise primarily targeting the Chest.'),
('Close-Grip Bench Press (Chest bias)', 'Chest', 'Barbell', '', 'The Close-Grip Bench Press (Chest bias) represents a barbell exercise primarily targeting the Chest.'),
('Guillotine Press', 'Chest', 'Barbell', '', 'The Guillotine Press represents a barbell exercise primarily targeting the Chest.'),
('Flat Dumbbell Bench Press', 'Chest', 'Dumbbell', '', 'The Flat Dumbbell Bench Press represents a dumbbell exercise primarily targeting the Chest.'),
('Incline Dumbbell Bench Press', 'Chest', 'Dumbbell', '', 'The Incline Dumbbell Bench Press represents a dumbbell exercise primarily targeting the Chest.'),
('Decline Dumbbell Bench Press', 'Chest', 'Dumbbell', '', 'The Decline Dumbbell Bench Press represents a dumbbell exercise primarily targeting the Chest.'),
('Neutral-Grip Dumbbell Press', 'Chest', 'Dumbbell', '', 'The Neutral-Grip Dumbbell Press represents a dumbbell exercise primarily targeting the Chest.'),
('Dumbbell Fly (Flat / Incline / Decline)', 'Chest', 'Dumbbell', '', 'The Dumbbell Fly (Flat / Incline / Decline) represents a dumbbell exercise primarily targeting the Chest.'),
('Dumbbell Squeeze Press', 'Chest', 'Dumbbell', '', 'The Dumbbell Squeeze Press represents a dumbbell exercise primarily targeting the Chest.'),
('Dumbbell Pullover', 'Chest', 'Dumbbell', '', 'The Dumbbell Pullover represents a dumbbell exercise primarily targeting the Chest.'),
('Lat Pulldown (Wide Grip)', 'Back', 'Machine', '', 'The Lat Pulldown (Wide Grip) represents a machine exercise primarily targeting the Back.'),
('Lat Pulldown (Close Neutral Grip)', 'Back', 'Machine', '', 'The Lat Pulldown (Close Neutral Grip) represents a machine exercise primarily targeting the Back.'),
('Lat Pulldown (Reverse Grip)', 'Back', 'Machine', '', 'The Lat Pulldown (Reverse Grip) represents a machine exercise primarily targeting the Back.'),
('Iso-Lateral Lat Pulldown', 'Back', 'Machine', '', 'The Iso-Lateral Lat Pulldown represents a machine exercise primarily targeting the Back.'),
('Assisted Pull-Up Machine', 'Back', 'Machine', '', 'The Assisted Pull-Up Machine represents a machine exercise primarily targeting the Back.'),
('Seated Cable Row Machine', 'Back', 'Cable', '', 'The Seated Cable Row Machine represents a cable exercise primarily targeting the Back.'),
('Chest-Supported Row Machine', 'Back', 'Machine', '', 'The Chest-Supported Row Machine represents a machine exercise primarily targeting the Back.'),
('Hammer Strength High Row', 'Back', 'Machine', '', 'The Hammer Strength High Row represents a machine exercise primarily targeting the Back.'),
('Hammer Strength Low Row', 'Back', 'Machine', '', 'The Hammer Strength Low Row represents a machine exercise primarily targeting the Back.'),
('T-Bar Row Machine', 'Back', 'Machine', '', 'The T-Bar Row Machine represents a machine exercise primarily targeting the Back.'),
('Plate-Loaded Row Machine', 'Back', 'Machine', '', 'The Plate-Loaded Row Machine represents a machine exercise primarily targeting the Back.'),
('Reverse Pec Deck (Rear Delt / Upper Back)', 'Back', 'Machine', '', 'The Reverse Pec Deck (Rear Delt / Upper Back) represents a machine exercise primarily targeting the Back.'),
('Back Extension Machine (45° / Horizontal)', 'Back', 'Machine', '', 'The Back Extension Machine (45° / Horizontal) represents a machine exercise primarily targeting the Back.'),
('Straight-Arm Pulldown (Rope / Bar)', 'Back', 'Cable', '', 'The Straight-Arm Pulldown (Rope / Bar) represents a cable exercise primarily targeting the Back.'),
('Single-Arm Lat Pulldown', 'Back', 'Cable', '', 'The Single-Arm Lat Pulldown represents a cable exercise primarily targeting the Back.'),
('Kneeling Lat Pulldown', 'Back', 'Cable', '', 'The Kneeling Lat Pulldown represents a cable exercise primarily targeting the Back.'),
('Face Pull (Rope)', 'Back', 'Cable', '', 'The Face Pull (Rope) represents a cable exercise primarily targeting the Back.'),
('Face Pull (Dual Handles)', 'Back', 'Cable', '', 'The Face Pull (Dual Handles) represents a cable exercise primarily targeting the Back.'),
('High Cable Row', 'Back', 'Cable', '', 'The High Cable Row represents a cable exercise primarily targeting the Back.'),
('Low Cable Row (Close / Wide)', 'Back', 'Cable', '', 'The Low Cable Row (Close / Wide) represents a cable exercise primarily targeting the Back.'),
('Conventional Deadlift', 'Back', 'Barbell', '', 'The Conventional Deadlift represents a barbell exercise primarily targeting the Back.'),
('Sumo Deadlift', 'Back', 'Barbell', '', 'The Sumo Deadlift represents a barbell exercise primarily targeting the Back.'),
('Bent-Over Row', 'Back', 'Barbell', '', 'The Bent-Over Row represents a barbell exercise primarily targeting the Back.'),
('Pendlay Row', 'Back', 'Barbell', '', 'The Pendlay Row represents a barbell exercise primarily targeting the Back.'),
('Rack Pull', 'Back', 'Barbell', '', 'The Rack Pull represents a barbell exercise primarily targeting the Back.'),
('Barbell Shrug', 'Back', 'Barbell', '', 'The Barbell Shrug represents a barbell exercise primarily targeting the Back.'),
('One-Arm Dumbbell Row', 'Back', 'Dumbbell', '', 'The One-Arm Dumbbell Row represents a dumbbell exercise primarily targeting the Back.'),
('Chest-Supported Dumbbell Row', 'Back', 'Dumbbell', '', 'The Chest-Supported Dumbbell Row represents a dumbbell exercise primarily targeting the Back.'),
('Dumbbell Shrug', 'Back', 'Dumbbell', '', 'The Dumbbell Shrug represents a dumbbell exercise primarily targeting the Back.'),
('Renegade Row', 'Back', 'Dumbbell', '', 'The Renegade Row represents a dumbbell exercise primarily targeting the Back.'),
('Hack Squat Machine', 'Legs', 'Machine', '', 'The Hack Squat Machine represents a machine exercise primarily targeting the Legs.'),
('Linear Hack Squat', 'Legs', 'Machine', '', 'The Linear Hack Squat represents a machine exercise primarily targeting the Legs.'),
('V-Squat Machine', 'Legs', 'Machine', '', 'The V-Squat Machine represents a machine exercise primarily targeting the Legs.'),
('Pendulum Squat', 'Legs', 'Machine', '', 'The Pendulum Squat represents a machine exercise primarily targeting the Legs.'),
('Belt Squat', 'Legs', 'Machine', '', 'The Belt Squat represents a machine exercise primarily targeting the Legs.'),
('Leg Press (Horizontal)', 'Legs', 'Machine', '', 'The Leg Press (Horizontal) represents a machine exercise primarily targeting the Legs.'),
('Leg Press (45°)', 'Legs', 'Machine', '', 'The Leg Press (45°) represents a machine exercise primarily targeting the Legs.'),
('Leg Press (Vertical)', 'Legs', 'Machine', '', 'The Leg Press (Vertical) represents a machine exercise primarily targeting the Legs.'),
('Smith Machine Squat', 'Legs', 'Machine', '', 'The Smith Machine Squat represents a machine exercise primarily targeting the Legs.'),
('Leg Extension Machine', 'Legs', 'Machine', '', 'The Leg Extension Machine represents a machine exercise primarily targeting the Legs.'),
('Sissy Squat Machine', 'Legs', 'Machine', '', 'The Sissy Squat Machine represents a machine exercise primarily targeting the Legs.'),
('Spanish Squat (Band)', 'Legs', 'Band', '', 'The Spanish Squat (Band) represents a band exercise primarily targeting the Legs.'),
('Lying Leg Curl', 'Legs', 'Machine', '', 'The Lying Leg Curl represents a machine exercise primarily targeting the Legs.'),
('Seated Leg Curl', 'Legs', 'Machine', '', 'The Seated Leg Curl represents a machine exercise primarily targeting the Legs.'),
('Standing Single-Leg Curl', 'Legs', 'Machine', '', 'The Standing Single-Leg Curl represents a machine exercise primarily targeting the Legs.'),
('Nordic Curl Bench', 'Legs', 'Machine', '', 'The Nordic Curl Bench represents a machine exercise primarily targeting the Legs.'),
('Glute-Ham Raise (GHR)', 'Legs', 'Machine', '', 'The Glute-Ham Raise (GHR) represents a machine exercise primarily targeting the Legs.'),
('Hip Thrust Machine', 'Legs', 'Machine', '', 'The Hip Thrust Machine represents a machine exercise primarily targeting the Legs.'),
('Barbell Hip Thrust', 'Legs', 'Barbell', '', 'The Barbell Hip Thrust represents a barbell exercise primarily targeting the Legs.'),
('Smith Machine Hip Thrust', 'Legs', 'Machine', '', 'The Smith Machine Hip Thrust represents a machine exercise primarily targeting the Legs.'),
('Cable Glute Kickback', 'Legs', 'Cable', '', 'The Cable Glute Kickback represents a cable exercise primarily targeting the Legs.'),
('Cable Pull-Through', 'Legs', 'Cable', '', 'The Cable Pull-Through represents a cable exercise primarily targeting the Legs.'),
('Frog Press Machine', 'Legs', 'Machine', '', 'The Frog Press Machine represents a machine exercise primarily targeting the Legs.'),
('Standing Calf Raise Machine', 'Legs', 'Machine', '', 'The Standing Calf Raise Machine represents a machine exercise primarily targeting the Legs.'),
('Seated Calf Raise Machine', 'Legs', 'Machine', '', 'The Seated Calf Raise Machine represents a machine exercise primarily targeting the Legs.'),
('Donkey Calf Raise Machine', 'Legs', 'Machine', '', 'The Donkey Calf Raise Machine represents a machine exercise primarily targeting the Legs.'),
('Leg Press Calf Raise', 'Legs', 'Machine', '', 'The Leg Press Calf Raise represents a machine exercise primarily targeting the Legs.'),
('Shoulder Press Machine', 'Shoulders', 'Machine', '', 'The Shoulder Press Machine represents a machine exercise primarily targeting the Shoulders.'),
('Incline Shoulder Press Machine', 'Shoulders', 'Machine', '', 'The Incline Shoulder Press Machine represents a machine exercise primarily targeting the Shoulders.'),
('Iso-Lateral Shoulder Press', 'Shoulders', 'Machine', '', 'The Iso-Lateral Shoulder Press represents a machine exercise primarily targeting the Shoulders.'),
('Plate-Loaded Shoulder Press', 'Shoulders', 'Machine', '', 'The Plate-Loaded Shoulder Press represents a machine exercise primarily targeting the Shoulders.'),
('Lateral Raise Machine', 'Shoulders', 'Machine', '', 'The Lateral Raise Machine represents a machine exercise primarily targeting the Shoulders.'),
('Dual-Function Lateral/Rear Delt Machine', 'Shoulders', 'Machine', '', 'The Dual-Function Lateral/Rear Delt Machine represents a machine exercise primarily targeting the Shoulders.'),
('Reverse Pec Deck', 'Shoulders', 'Machine', '', 'The Reverse Pec Deck represents a machine exercise primarily targeting the Shoulders.'),
('Upright Row Machine', 'Shoulders', 'Machine', '', 'The Upright Row Machine represents a machine exercise primarily targeting the Shoulders.'),
('Cable Lateral Raise', 'Shoulders', 'Cable', '', 'The Cable Lateral Raise represents a cable exercise primarily targeting the Shoulders.'),
('Cable Front Raise', 'Shoulders', 'Cable', '', 'The Cable Front Raise represents a cable exercise primarily targeting the Shoulders.'),
('Cable Rear Delt Fly', 'Shoulders', 'Cable', '', 'The Cable Rear Delt Fly represents a cable exercise primarily targeting the Shoulders.'),
('Cable Upright Row', 'Shoulders', 'Cable', '', 'The Cable Upright Row represents a cable exercise primarily targeting the Shoulders.'),
('Overhead Press', 'Shoulders', 'Barbell', '', 'The Overhead Press represents a barbell exercise primarily targeting the Shoulders.'),
('Push Press', 'Shoulders', 'Barbell', '', 'The Push Press represents a barbell exercise primarily targeting the Shoulders.'),
('Bradford Press', 'Shoulders', 'Barbell', '', 'The Bradford Press represents a barbell exercise primarily targeting the Shoulders.'),
('Upright Row', 'Shoulders', 'Barbell', '', 'The Upright Row represents a barbell exercise primarily targeting the Shoulders.'),
('Dumbbell Shoulder Press', 'Shoulders', 'Dumbbell', '', 'The Dumbbell Shoulder Press represents a dumbbell exercise primarily targeting the Shoulders.'),
('Arnold Press', 'Shoulders', 'Dumbbell', '', 'The Arnold Press represents a dumbbell exercise primarily targeting the Shoulders.'),
('Lateral Raise (Standing / Seated)', 'Shoulders', 'Dumbbell', '', 'The Lateral Raise (Standing / Seated) represents a dumbbell exercise primarily targeting the Shoulders.'),
('Front Raise', 'Shoulders', 'Dumbbell', '', 'The Front Raise represents a dumbbell exercise primarily targeting the Shoulders.'),
('Rear Delt Fly', 'Shoulders', 'Dumbbell', '', 'The Rear Delt Fly represents a dumbbell exercise primarily targeting the Shoulders.'),
('Lean-Away Lateral Raise', 'Shoulders', 'Dumbbell', '', 'The Lean-Away Lateral Raise represents a dumbbell exercise primarily targeting the Shoulders.'),
('Preacher Curl Machine', 'Arms', 'Machine', '', 'The Preacher Curl Machine represents a machine exercise primarily targeting the Arms.'),
('Standing Cable Curl (Straight Bar)', 'Arms', 'Cable', '', 'The Standing Cable Curl (Straight Bar) represents a cable exercise primarily targeting the Arms.'),
('Standing Cable Curl (EZ Bar)', 'Arms', 'Cable', '', 'The Standing Cable Curl (EZ Bar) represents a cable exercise primarily targeting the Arms.'),
('Standing Cable Curl (Rope)', 'Arms', 'Cable', '', 'The Standing Cable Curl (Rope) represents a cable exercise primarily targeting the Arms.'),
('Low Pulley Single-Arm Curl', 'Arms', 'Machine', '', 'The Low Pulley Single-Arm Curl represents a machine exercise primarily targeting the Arms.'),
('Bayesian Curl (Behind-Body Cable)', 'Arms', 'Cable', '', 'The Bayesian Curl (Behind-Body Cable) represents a cable exercise primarily targeting the Arms.'),
('Spider Curl Machine', 'Arms', 'Machine', '', 'The Spider Curl Machine represents a machine exercise primarily targeting the Arms.'),
('Barbell Curl', 'Arms', 'Barbell', '', 'The Barbell Curl represents a barbell exercise primarily targeting the Arms.'),
('EZ-Bar Curl', 'Arms', 'Bodyweight', '', 'The EZ-Bar Curl represents a bodyweight exercise primarily targeting the Arms.'),
('Dumbbell Curl', 'Arms', 'Dumbbell', '', 'The Dumbbell Curl represents a dumbbell exercise primarily targeting the Arms.'),
('Hammer Curl', 'Arms', 'Bodyweight', '', 'The Hammer Curl represents a bodyweight exercise primarily targeting the Arms.'),
('Incline Dumbbell Curl', 'Arms', 'Dumbbell', '', 'The Incline Dumbbell Curl represents a dumbbell exercise primarily targeting the Arms.'),
('Concentration Curl', 'Arms', 'Bodyweight', '', 'The Concentration Curl represents a bodyweight exercise primarily targeting the Arms.'),
('Cable (Highly Detailed)', 'Arms', 'Cable', '', 'The Cable (Highly Detailed) represents a cable exercise primarily targeting the Arms.'),
('Rope Tricep Pushdown', 'Arms', 'Bodyweight', '', 'The Rope Tricep Pushdown represents a bodyweight exercise primarily targeting the Arms.'),
('Straight Bar Cable Pushdown', 'Arms', 'Cable', '', 'The Straight Bar Cable Pushdown represents a cable exercise primarily targeting the Arms.'),
('EZ-Bar Cable Pushdown', 'Arms', 'Cable', '', 'The EZ-Bar Cable Pushdown represents a cable exercise primarily targeting the Arms.'),
('Reverse-Grip Pushdown', 'Arms', 'Bodyweight', '', 'The Reverse-Grip Pushdown represents a bodyweight exercise primarily targeting the Arms.'),
('Single-Arm Cable Pushdown', 'Arms', 'Cable', '', 'The Single-Arm Cable Pushdown represents a cable exercise primarily targeting the Arms.'),
('Overhead Cable Extension (Rope)', 'Arms', 'Cable', '', 'The Overhead Cable Extension (Rope) represents a cable exercise primarily targeting the Arms.'),
('Overhead Cable Extension (Bar)', 'Arms', 'Cable', '', 'The Overhead Cable Extension (Bar) represents a cable exercise primarily targeting the Arms.'),
('Cross-Body Cable Extension', 'Arms', 'Cable', '', 'The Cross-Body Cable Extension represents a cable exercise primarily targeting the Arms.'),
('Tricep Extension Machine', 'Arms', 'Machine', '', 'The Tricep Extension Machine represents a machine exercise primarily targeting the Arms.'),
('Dip Assist Machine', 'Arms', 'Machine', '', 'The Dip Assist Machine represents a machine exercise primarily targeting the Arms.'),
('Seated Tricep Press Machine', 'Arms', 'Machine', '', 'The Seated Tricep Press Machine represents a machine exercise primarily targeting the Arms.'),
('Close-Grip Bench Press', 'Arms', 'Bodyweight', '', 'The Close-Grip Bench Press represents a bodyweight exercise primarily targeting the Arms.'),
('Skull Crushers (BB / EZ / DB)', 'Arms', 'Bodyweight', '', 'The Skull Crushers (BB / EZ / DB) represents a bodyweight exercise primarily targeting the Arms.'),
('Dumbbell Overhead Extension', 'Arms', 'Dumbbell', '', 'The Dumbbell Overhead Extension represents a dumbbell exercise primarily targeting the Arms.'),
('JM Press', 'Arms', 'Bodyweight', '', 'The JM Press represents a bodyweight exercise primarily targeting the Arms.'),
('Bench Dips', 'Arms', 'Bodyweight', '', 'The Bench Dips represents a bodyweight exercise primarily targeting the Arms.'),
('Ab Crunch Machine', 'Core', 'Machine', '', 'The Ab Crunch Machine represents a machine exercise primarily targeting the Core.'),
('Rotary Torso Machine', 'Core', 'Machine', '', 'The Rotary Torso Machine represents a machine exercise primarily targeting the Core.'),
('Roman Chair', 'Core', 'Machine', '', 'The Roman Chair represents a machine exercise primarily targeting the Core.'),
('Captain’s Chair', 'Core', 'Machine', '', 'The Captain’s Chair represents a machine exercise primarily targeting the Core.'),
('Cable Crunch', 'Core', 'Cable', '', 'The Cable Crunch represents a cable exercise primarily targeting the Core.'),
('Cable Woodchopper (High / Low)', 'Core', 'Cable', '', 'The Cable Woodchopper (High / Low) represents a cable exercise primarily targeting the Core.'),
('Pallof Press', 'Core', 'Cable', '', 'The Pallof Press represents a cable exercise primarily targeting the Core.'),
('Hanging Leg Raise', 'Core', 'Bodyweight', '', 'The Hanging Leg Raise represents a bodyweight exercise primarily targeting the Core.'),
('Decline Sit-up', 'Core', 'Bodyweight', '', 'The Decline Sit-up represents a bodyweight exercise primarily targeting the Core.'),
('Weighted Plank', 'Core', 'Bodyweight', '', 'The Weighted Plank represents a bodyweight exercise primarily targeting the Core.'),
('Ab Wheel Rollout', 'Core', 'Bodyweight', '', 'The Ab Wheel Rollout represents a bodyweight exercise primarily targeting the Core.'),
('Dragon Flag', 'Core', 'Bodyweight', '', 'The Dragon Flag represents a bodyweight exercise primarily targeting the Core.'),
('Rowing Erg', 'Cardio', 'Machine', '', 'The Rowing Erg represents a machine exercise primarily targeting the Cardio.'),
('Ski Erg', 'Cardio', 'Machine', '', 'The Ski Erg represents a machine exercise primarily targeting the Cardio.'),
('Air Bike', 'Cardio', 'Machine', '', 'The Air Bike represents a machine exercise primarily targeting the Cardio.'),
('Treadmill Incline Walk', 'Cardio', 'Machine', '', 'The Treadmill Incline Walk represents a machine exercise primarily targeting the Cardio.'),
('Stair Climber', 'Cardio', 'Machine', '', 'The Stair Climber represents a machine exercise primarily targeting the Cardio.'),
('Kettlebell Swings', 'Cardio', 'Kettlebell', '', 'The Kettlebell Swings represents a kettlebell exercise primarily targeting the Cardio.'),
('Farmer’s Walk', 'Cardio', 'Machine', '', 'The Farmer’s Walk represents a machine exercise primarily targeting the Cardio.'),
('Sled Push', 'Cardio', 'Machine', '', 'The Sled Push represents a machine exercise primarily targeting the Cardio.'),
('Sled Pull', 'Cardio', 'Machine', '', 'The Sled Pull represents a machine exercise primarily targeting the Cardio.'),
('Band Pull-Apart', 'Other', 'Band', '', 'The Band Pull-Apart represents a band exercise primarily targeting the Other.'),
('Cable External Rotation', 'Other', 'Cable', '', 'The Cable External Rotation represents a cable exercise primarily targeting the Other.'),
('Cable Internal Rotation', 'Other', 'Cable', '', 'The Cable Internal Rotation represents a cable exercise primarily targeting the Other.'),
('Scapular Pulldown', 'Other', 'Other', '', 'The Scapular Pulldown represents a other exercise primarily targeting the Other.'),
('Tibialis Raise Machine', 'Other', 'Machine', '', 'The Tibialis Raise Machine represents a machine exercise primarily targeting the Other.'),
('Hip Abduction Machine', 'Other', 'Machine', '', 'The Hip Abduction Machine represents a machine exercise primarily targeting the Other.'),
('Hip Adduction Machine', 'Other', 'Machine', '', 'The Hip Adduction Machine represents a machine exercise primarily targeting the Other.')
ON CONFLICT (name) DO UPDATE SET muscle_group = EXCLUDED.muscle_group, equipment = EXCLUDED.equipment, description = EXCLUDED.description;
